services:
  frontend:
    build: ./packages/frontend
    ports:
      - '80:80'
    depends_on:
      - flask
    networks:
      - custom_network

  flask:
    build: ./packages/IA
    ports:
      - '5000:5000'
    networks:
      - custom_network

  backend:
    build: ./packages/backend
    ports:
      - '3000:3000'
    volumes:
      - ./packages/backend:/app
      - ./packages/backend/uploads:/app/uploads
    networks:
      - custom_network
    env_file:
      - ./packages/backend/.env

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    networks:
      - custom_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ['postgres']

networks:
  custom_network:
    driver: bridge

volumes:
  postgres_data:
