services:
  frontend:
    build: ./packages/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - custom_network
    environment:
      - NEXT_PUBLIC_API_URL="http://backend:3000"

  flask:
    build: ./packages/IA
    ports:
      - "5000:5000"
    networks:
      - custom_network

  backend:
    build: ./packages/backend
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend:/app
      - ./packages/backend/uploads:/app/uploads
    networks:
      - custom_network
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_SSL=false
      - DB_PORT=5432
      - FLASK_API_URL=http://flask:5000
    depends_on:
      - db
      - flask

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    networks:
      - custom_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres"]

networks:
  custom_network:
    driver: bridge

volumes:
  postgres_data:
