services:
  frontend:
    build: ./packages/frontend
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - custom_network
    environment:
      - NEXT_PUBLIC_API_URL=http://flask:5000

  flask:
    build: ./packages/IA
    ports:
      - "5000:5000"
    networks:
      - custom_network

  backend:
    build: ./packages/backend
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend:/app
      - ./packages/backend/uploads:/app/uploads
    networks:
      - custom_network
    env_file:
      - ./packages/backend/.env.local

networks:
  custom_network:
    driver: bridge
