import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    root: { flex: 1 },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 13,
        borderBottomWidth: 1,
    },
    brand: { fontSize: 18, fontWeight: '700' },
    menuBtn: {
        width: 36,
        height: 36,
        borderRadius: 8,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    drawerOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.45)' },
    drawerPanel: {
        position: 'absolute',
        right: 0,
        shadowColor: '#000',
        shadowOffset: { width: -2, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 16,
    },
    drawerSafeArea: { flex: 1 },
    drawerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 18,
        paddingVertical: 16,
        borderBottomWidth: 1,
    },
    drawerTitle: { fontSize: 17, fontWeight: '700' },
    drawerCloseBtn: {
        width: 30,
        height: 30,
        borderRadius: 8,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    drawerCloseIcon: { fontSize: 15, lineHeight: 17 },
    drawerUserName: { fontSize: 16, fontWeight: '600', paddingHorizontal: 18, paddingVertical: 14 },
    drawerItem: { paddingHorizontal: 18, paddingVertical: 14 },
    drawerItemRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    drawerItemText: { fontSize: 15, fontWeight: '500' },
    drawerDivider: { height: 1, marginHorizontal: 10 },
    scroll: { flex: 1, paddingHorizontal: 16 },
    pageTitle: { marginTop: 16, marginBottom: 4 },
    title: { fontSize: 22, fontWeight: '700', marginBottom: 4 },
    subtitle: { fontSize: 13 },
    tabsContainer: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        marginTop: 14,
        marginBottom: 16,
    },
    tab: {
        flex: 1,
        paddingVertical: 11,
        alignItems: 'center',
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
    },
    activeTab: { borderBottomWidth: 2 },
    tabText: { fontSize: 13 },
    content: { gap: 0 },
    card: {
        borderRadius: 12,
        borderWidth: 1,
        padding: 16,
        marginBottom: 16,
    },
    cardTitle: { fontSize: 16, fontWeight: '600', marginBottom: 4 },
    cardDescription: { fontSize: 13, marginBottom: 14 },
    cropLabel: { fontSize: 13, fontWeight: '600', marginBottom: 8 },
    cropRequired: { color: '#ef4444' },
    cropRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
    cropChip: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 16,
        borderWidth: 1,
    },
    cropChipText: { fontSize: 13, fontWeight: '500' },
    imagePreview: {
        borderRadius: 8,
        overflow: 'hidden',
        marginBottom: 12,
        minHeight: 160,
        justifyContent: 'center',
        alignItems: 'center',
    },
    placeholderInner: { alignItems: 'center', paddingVertical: 32 },
    placeholderIcon: {
        width: 60,
        height: 60,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
    },
    placeholderText: { fontSize: 13 },
    fileName: { fontSize: 11, marginBottom: 10 },
    captureRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
    captureBtn: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 8,
        alignItems: 'center',
    },
    captureBtnText: { color: '#fff', fontWeight: '600', fontSize: 13 },
    btnRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    usageCounter: { fontSize: 11, textAlign: 'right', marginBottom: 6 },
    analyzeBtn: { paddingVertical: 13, borderRadius: 8, alignItems: 'center' },
    analyzeBtnText: { color: '#fff', fontWeight: '600', fontSize: 14 },
    emptyState: { paddingVertical: 32, alignItems: 'center' },
    statsEmptyIcon: { marginBottom: 12 },
    emptyStateIcon: { marginBottom: 12 },
    emptyText: { fontSize: 13, textAlign: 'center', lineHeight: 20 },
    loadingState: { paddingVertical: 40, alignItems: 'center' },
    loadingText: { fontSize: 15, fontWeight: '500' },
    loadingSubtext: { fontSize: 12, marginTop: 6 },
    resultSection: { gap: 14 },
    resultRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flexWrap: 'wrap',
    },
    resultLabel: { fontSize: 12, fontWeight: '500', marginBottom: 4 },
    resultValue: { fontSize: 17, fontWeight: '600' },
    resultBody: { fontSize: 13, lineHeight: 20, marginTop: 2 },
    divider: { height: 1 },
    badge: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 6,
    },
    badgeText: { color: '#fff', fontSize: 11, fontWeight: '600' },
    badgeOutline: {
        paddingHorizontal: 7,
        paddingVertical: 2,
        borderRadius: 6,
        borderWidth: 1,
    },
    badgeOutlineText: { fontSize: 11, fontWeight: '600' },
    alertBox: {
        borderRadius: 8,
        borderWidth: 1,
        padding: 12,
        gap: 4,
    },
    alertTitle: { fontSize: 13, fontWeight: '600' },
    alertBody: { fontSize: 12, lineHeight: 18 },
    tipsGrid: { gap: 10, marginTop: 4 },
    tipCard: { borderRadius: 8, borderWidth: 1, padding: 12 },
    tipTitle: { fontSize: 13, fontWeight: '600', marginBottom: 4 },
    tipDesc: { fontSize: 12, lineHeight: 18 },
    historyList: { marginTop: 8 },
    historyItem: {
        paddingVertical: 12,
        gap: 10,
    },
    historyTopRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 10,
    },
    historyThumb: { width: 56, height: 56, borderRadius: 8 },
    historyMain: { flex: 1 },
    historyTitle: { fontSize: 13, fontWeight: '600', marginBottom: 3 },
    historyCrop: { fontSize: 12, marginBottom: 2 },
    historyDate: { fontSize: 11 },
    historyPctBadges: { alignItems: 'flex-end', gap: 4 },
    historyActionsRow: { flexDirection: 'row', gap: 8 },
    historyActionBtn: { flex: 1 },
    historyBtnRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4 },
    statsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginBottom: 20,
    },
    statCard: {
        flexBasis: '47%',
        flexGrow: 1,
        borderRadius: 10,
        borderWidth: 1,
        padding: 14,
    },
    statLabel: { fontSize: 12 },
    statValue: { fontSize: 24, fontWeight: '700', marginTop: 6 },
    statChange: { fontSize: 11, marginTop: 6, lineHeight: 15 },
    diseasesTitle: { fontSize: 15, fontWeight: '600' },
    diseasesList: { gap: 12 },
    diseaseItem: { gap: 6 },
    diseaseHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    diseaseName: { fontSize: 13, fontWeight: '500' },
    diseasePct: { fontSize: 12 },
    progressBar: { height: 6, borderRadius: 3, overflow: 'hidden' },
    progressFill: { height: '100%', borderRadius: 3 },
    chartCard: { marginTop: 22 },
    chartSubtitle: { fontSize: 12, marginTop: 2, marginBottom: 4 },
    chartArea: { height: 200, marginTop: 10, position: 'relative' },
    chartAxisRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 4,
    },
    chartAxisLabel: { fontSize: 11 },
    chartTooltip: {
        position: 'absolute',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 6,
    },
    chartTooltipMulti: { top: 4, maxWidth: 160 },
    chartTooltipPeriod: { fontSize: 11, fontWeight: '600' },
    chartTooltipValue: { fontSize: 11, marginTop: 2 },
    legendWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginTop: 14,
    },
    legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6, maxWidth: 150 },
    legendSwatch: { width: 10, height: 10, borderRadius: 2 },
    legendLabel: { fontSize: 11 },
    peakList: { marginTop: 18, gap: 10 },
    peakRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    peakName: { flex: 1, fontSize: 12, fontWeight: '500' },
    peakPeriod: { fontSize: 11 },
    peakCount: { fontSize: 12, fontWeight: '700', minWidth: 24, textAlign: 'right' },
    chatBtn: {
        marginTop: 6,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    chatBtnText: { color: '#fff', fontWeight: '600', fontSize: 14 },
    reportBtn: {
        marginTop: 6,
        paddingVertical: 12,
        borderRadius: 8,
        borderWidth: 1,
        alignItems: 'center',
    },
    reportBtnText: { fontWeight: '600', fontSize: 14 },
    reportLockedText: { fontSize: 11, textAlign: 'center', marginTop: 6 },
    historyChatBtn: {
        marginTop: 4,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 6,
        borderWidth: 1,
        alignItems: 'center',
    },
    historyChatBtnText: { fontSize: 11, fontWeight: '600' },
    filterLabel: { fontSize: 12, fontWeight: '600', marginTop: 14, marginBottom: 6 },
    filterRow: { flexDirection: 'row', marginBottom: 4 },
    filterChip: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        borderWidth: 1,
        marginRight: 8,
    },
    filterChipText: { fontSize: 12, fontWeight: '500' },
    orderToggle: {
        marginTop: 12,
        marginBottom: 4,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 8,
        borderWidth: 1,
        alignSelf: 'flex-start',
    },
    orderToggleText: { fontSize: 12, fontWeight: '500' },
});
